services:

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.mby:
        class: AppBundle\Extension\MbyTwigExtension
        arguments: [ "@csrf_intent_repository", "@form.csrf_provider", "@security.context" ]
        tags:
            - { name: twig.extension }

    privilege_manager:
        class:     Mby\CommunityBundle\Service\PrivilegeManager
        arguments: [ "@doctrine.orm.entity_manager" ]
    responsibility_manager:
        class:     Mby\CommunityBundle\Service\ResponsibilityManager
        arguments: [ "@doctrine.orm.entity_manager" ]
    community_manager:
        class:     Mby\CommunityBundle\Service\CommunityManager
        arguments: [ "@doctrine.orm.entity_manager", "@privilege_manager" ]
    season_manager:
        class:     Mby\CommunityBundle\Service\SeasonManager
        arguments: [ "@doctrine.orm.entity_manager", "@privilege_manager" ]
    membership_manager:
        class:     Mby\CommunityBundle\Service\MembershipManager
        arguments: [ "@doctrine.orm.entity_manager" , "@privilege_manager", "@responsibility_manager"  ]

    community_facade:
        class:     Mby\CommunityBundle\Service\Facade\CommunityFacade
        arguments: [ "@doctrine.orm.entity_manager", "@community_manager", "@privilege_manager" ]
    season_facade:
        class:     Mby\CommunityBundle\Service\Facade\SeasonFacade
        arguments: [ "@doctrine.orm.entity_manager", "@season_manager", "@privilege_manager" ]
    membership_facade:
        class:     Mby\CommunityBundle\Service\Facade\MembershipFacade
        arguments: [ "@doctrine.orm.entity_manager", "@membership_manager", "@privilege_manager" ]

    csrf_intent_repository:
        class:     Mby\CommunityBundle\Service\CsrfIntentRepository

    form.type.manage_community:
        class: Mby\CommunityBundle\Form\Type\ManageCommunityType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type, alias: manage_community }
    form.type.season:
        class: Mby\CommunityBundle\Form\Type\AdminSeasonType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type, alias: admin_season }