services:

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    privilege_manager:
        class:     Mby\CommunityBundle\Service\PrivilegeManager
        arguments: [ "@doctrine.orm.entity_manager" ]
    responsibility_manager:
        class:     Mby\CommunityBundle\Service\ResponsibilityManager
        arguments: [ "@doctrine.orm.entity_manager" ]
    community_manager:
        class:     Mby\CommunityBundle\Service\CommunityManager
        arguments: [ "@doctrine.orm.entity_manager", "@privilege_manager" ]
    season_manager:
        class:     Mby\CommunityBundle\Service\SeasonManager
        arguments: [ "@doctrine.orm.entity_manager", "@privilege_manager" ]
    membership_manager:
        class:     Mby\CommunityBundle\Service\MembershipManager
        arguments: [ "@doctrine.orm.entity_manager" , "@privilege_manager", "@responsibility_manager"  ]

    community_facade:
        class:     Mby\CommunityBundle\Service\Facade\CommunityFacade
        arguments: [ "@doctrine.orm.entity_manager", "@community_manager", "@privilege_manager" ]

    form.type.manage_community:
        class: Mby\CommunityBundle\Form\Type\ManageCommunityType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type, alias: manage_community }