<?php

namespace Mby\CommunityBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Mby\UserBundle\Entity\User;

/**
 * CommunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityRepository extends EntityRepository
{

    public function findAllUserCommunities(User $user)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                '   SELECT c, s, m, r
                    FROM MbyCommunityBundle:Community c
                        JOIN c.seasons s
                        JOIN s.memberships m
                        JOIN m.responsibilities r
                    WHERE m.user = :userId
                    ORDER BY c.name, s.fromDate
                    '
            )
            ->setParameter('userId', $user->getId());
        
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            throw $e;
        }
        
    }

    public function findAllCommunities()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                '   SELECT c
                    FROM MbyCommunityBundle:Community c
                        JOIN c.seasons s
                    ORDER BY c.name, s.fromDate
                    '
            );
        
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            throw $e;
        }
        
    }


}
