<?php

namespace Mby\CommunityBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Mby\UserBundle\Entity\User;

/**
 * MembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipRepository extends EntityRepository
{
	public function findAllUserMemberships(User $user)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                '	SELECT ms 
                	FROM MbyCommunityBundle:Membership ms 
                		JOIN MbyCommunityBundle:Responsibilty resp
                		JOIN MbyCommunityBundle:Season sea
                        JOIN MbyCommunityBundle:Community com
                	WHERE ms.user_id = :userId
                	ORDER BY com.name ASC, sea.fromDate ASC, ms.fromDate ASC'
            )
            ->setParameter('userId', $user->getId());
        
        try {
	        return $query->getResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        throw $e;
	    }
        
    }

    public function loadResponsibilities(User $user, Season $season)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                '   SELECT m, r
                    FROM MbyCommunityBundle:Membership m
                        JOIN m.responsibilities r
                    WHERE m.user = :userId AND m.season = :seasonId
                    ORDER BY r.id ASC
                '
            )
            ->setParameter('userId', $user->getId())
            ->setParameter('seasonId', $season->getId());
        
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            throw $e;
        }
        
    }
    
}
