<?php

namespace Mby\CommunityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrivilegeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivilegeRepository extends EntityRepository
{
	const OWNER_CODE = 'owner';
	const ADMIN_CODE = 'admin';
    const MODERATOR_CODE = 'moderator';

}
