<?php

namespace Mby\CommunityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResponsibilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsibilityRepository extends EntityRepository
{

	const APPLICANT_NAME = 'applicant';
    const MEMBER_NAME = 'member';

	public function findByName(string $name)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM MbyCommunityBundle:Responsibility r WHERE r.name = :respName'
            )
            ->setParameter('respName', $name)
            ->getSingleResult();
    }

}
